export enum Pages {
  PASSWORD_RESET = "password-reset",
  VERIFY_EMAIL = "verify-email",
  SUMMARY = "summary",
  PROJECTS = "projects",
  TASKS = "tasks",
  Enquires = "Enquires",
  EMPLOYEES = "employees",
  MANAGERS = "managers",
  CHAT = "chat",
  ATTENDANCE = "attendance",
  CALENDAR = "calendar",
  CATEGORIES = "departments",
  PROFILE = "profile",
  GROUPS="groups",
}
